
name: Daily News

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 15 * * *  # every 23:59 UTC +8

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-daily-news:
    runs-on: ubuntu-latest

    env:
      AI_PROVIDER: openai
      GPT_MODEL_NAME: gpt-4o
      GPT_BASE_URL: ${{ secrets.GPT_BASE_URL }}
      GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
      CZ_API_KEY: ${{ secrets.CZ_API_KEY }}
      MAX_ARTICLE_NUMS: 25
      RSS_CACHE_ENABLE: true

    steps:
      - name: Before Execute
        # You may pin to the exact commit or the version.
        run: |
          echo $GPT_API_KEY
          echo $GPT_BASE_URL
          echo $AI_PROVIDER
          ls -l

      - name: Python print secrets
        run: |
          import os
          for q in (os.getenv("GPT_BASE_URL")):
            print(q)
        shell: python

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Create Daily News
        # You may pin to the exact commit or the version.
        run: python main.py

#      - name: To podcast(本地执行，不在github action执行，原因是coze.cn只能在中国用）
#        run: python convert_article_url_to_podcast.py

      # Runs a set of commands using the runners shell
      - name: push to origin main
        run: |
          echo "start push"
          git config --global user.name "shibing624"
          git config --global user.email "shibing624@126.com"
          git pull --rebase
    
          git add news/*.md
          git commit -m "$(date '+%Y-%m-%d')"
          git pull
          git push
          
          echo "git push commit done"
          
